FROM ubuntu

LABEL maintainer="Jiangda He. mail: hejiangda@gmail.com"

ENV OPENCV_VERSION=4.5.5

ENV BUILD="autoconf \
  ca-certificates \
  automake \
  build-essential \
  crossbuild-essential-arm64  \
  cmake \
  git-core \
  meson \
  ninja-build \
  pkg-config \
  texinfo \
  wget \
  yasm \
  zlib1g-dev \
  nasm"

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install -y --no-install-recommends ${BUILD}


WORKDIR /root
RUN mkdir -p ffmpeg_sources bin

RUN cd /root/ffmpeg_sources && \
wget -O ffmpeg-snapshot.tar.bz2 https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 && \
tar xjvf ffmpeg-snapshot.tar.bz2

RUN mkdir -p /root/zlib && cd /root/zlib && wget -O zlib.tar.gz https://zlib.net/zlib-1.2.12.tar.gz && \
    tar xzvf zlib.tar.gz && cd zlib-1.2.12/ && mkdir build && \
    CHOST=aarch64 CC=aarch64-linux-gnu-gcc \
    AR=aarch64-linux-gnu-ar \
    RANLIB=aarch64-linux-gnu-ranlib \
    ./configure --prefix=$(pwd)/build --includedir=/usr/aarch64-linux-gnu/include --libdir=/usr/aarch64-linux-gnu/lib && \
    make -j$(nproc)

RUN cd /root/zlib/zlib-1.2.12/ && make install

ENV TARGETMACH=arm-linux
ENV BUILDMACH=i686-pc-linux-gnu-
ENV CROSS=aarch64-linux-gnu-
ENV CC=${CROSS}gcc
ENV LD=${CROSS}ld
ENV AS=${CROSS}as
ENV CXX=${CROSS}g++
RUN mkdir -p /root/libdrm
WORKDIR /root/libdrm
RUN git clone https://gitlab.freedesktop.org/mesa/drm.git && mkdir -p /root/libdrm/drm/build
RUN cd drm && meson builddir/
RUN ninja -C builddir/ install


WORKDIR /root
RUN cd /root/ffmpeg_sources/ffmpeg && \
PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
  --prefix="$HOME/ffmpeg_build" \
  --enable-cross-compile \
  --cross-prefix=aarch64-linux-gnu- \
  --target-os=linux \
  --cc=aarch64-linux-gnu-gcc \
  --cxx=aarch64-linux-gnu-g++ \
  --pkg-config-flags="--static" \
  --extra-cflags="-I$HOME/ffmpeg_build/include" \
  --extra-ldflags="--static -L$HOME/ffmpeg_build/lib" \
  --extra-libs="-lpthread -lm" \
  --arch="arm" \
  --bindir="$HOME/bin" \
    --disable-x86asm --enable-parsers --disable-decoders --enable-decoder=h264 --enable-decoder=aac --disable-encoders --disable-muxers --enable-muxer=mp4 --disable-demuxers  --disable-filters --disable-bsfs --enable-ffmpeg \
    --enable-encoder=mjpeg,png \
    --enable-decoder=mjpeg,png \
    --enable-demuxer=image2 \
    --enable-protocol=file \
    --enable-zlib \
    --enable-libdrm \
    && \
PATH="$HOME/bin:$PATH" make -j12 && \
make install -j12 && \
hash -r
